#!/usr/bin/env bash
# Responsible of the following:
#   Creating a file /var/run/myscript.pid that contains the script PID.
#   Displaying "To infinity and beyond" indefinitely
#   Displaying "I hate the kill command" upon receiving a SIGTERM
#   Displaying "Y U no love me?!" upon receiving a SIGINT
#   Deleting the file /var/run/myscript.pid and terminates upon
#   receive a SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
