#!/usr/bin/env bash

# Shows the Process ID (PID) and process name
# of processes with "bash" in their names.
# Use the 'pgrep' command with the '-l' option
# to list processes with "bash" in their names.

pgrep bash -l
