#!/usr/bin/env bash
# Displaying "To infinity and beyond" indefinitely with
# a sleep 2 between each every iteration.
# Displaying "I am invincible!!!" between eveery iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done