#!/usr/bin/env bash
# Displaying numbers from 1 to 100 list format.
# Displaying "FizzBuzz" when number is a multiple of 3 and 5.
# Displaying "Fizz" when number is a multiple of 3.
# Displaying "Buzz" when number is a multiple of 5.
# Otherwise, displays number.

for num in {1..100}
do
  if (( num % 3 == 0 && num % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( num % 3 == 0 ))
  then
    echo "Fizz"
  elif (( num % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$num"
  fi
done