#!/usr/bin/env bash
# Displaying the "Best School" 10 times using while loop.
# At the 9th iteration, displays "Hi" before "Best School".

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done