#!/usr/bin/env bash
# Displaying the contents of the current directory in list format.
# Only displaying the part of name after the first dash. 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done